[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.104.1",
    "librosa==0.10.1",
    "numpy==1.24.3",
    "pydub==0.25.1",
    "python-multipart==0.0.6",
    "soundfile==0.12.1",
    "uvicorn[standard]==0.24.0",
]
