// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/6/2025, 4:07:01 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/runner/workspace/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/frontend/plugins/**/*.{js,ts,mjs}","/home/runner/workspace/frontend/composables/**/*.{js,ts,mjs}","/home/runner/workspace/frontend/utils/**/*.{js,ts,mjs}","/home/runner/workspace/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/frontend/app.config.{js,ts,mjs}","/home/runner/workspace/frontend/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;